wandb_version: 1

Learning Rate:
  desc: null
  value: 0.3
_wandb:
  desc: null
  value:
    cli_version: 0.10.24
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.9
    t:
      1:
      - 1
      - 5
      4: 3.6.9
      5: 0.10.24
      8:
      - 1
      - 5
metacriteria:
  desc: null
  value: metacriteria_attractive
pretrained:
  desc: null
  value: false
